### ISSUE TITLE
新增功能

### ISSUE THREAD

**Issue by nuanxinqing123** [remiliacn/qqBot#10]
有了YoutuBe的直播订阅，有没有B站的直播订阅相关呢？

**Comment by remiliacn** [comment]
如果有相应需求可以看一下这个功能https://github.com/remiliacn/qqBot/blob/master/awesome/plugins/get_tweet/get_tweet.py#L24

https://github.com/remiliacn/qqBot/blob/master/awesome/plugins/get_tweet/get_tweet.py#L306

但是由于我个人没什么相应需求所以这个功能没进行过完整的测试，可能会有bug。
