### ISSUE TITLE
ImportError: cannot import name 'Expression_T' from 'nonebot.typing' (D:\Python\IDLE\lib\site-packages\nonebot\typing.py)

### ISSUE THREAD

**Issue by PH-botHQ** [remiliacn/qqBot#12]
from .typing import Expression_T, PermissionPolicy_T
ImportError: cannot import name 'Expression_T' from 'nonebot.typing' (D:\Python\IDLE\lib\site-packages\nonebot\typing.py)

**Comment by billma007** [comment]
可能是nonebot1和nb2之间切换的时候造成的兼容问题。如果实在不行，把nonebot删掉再重新安装就可
