### ISSUE TITLE
Cannot install -r requirements.txt (line 13) and urllib3>=1.26.5

### ISSUE THREAD

**Issue by test-black** [remiliacn/qqBot#13]
Ubuntu 20.04
Python 3.8.3
pip 21.3.1

![Snipaste_2022-01-13_17-16-53](https://user-images.githubusercontent.com/28062894/149301254-d0ec1930-1785-4d72-897c-5b914e42ccb8.png)

**Comment by test-black** [comment]
移除 requirements.txt 中 urllib3 版本号解决问题

**Comment by test-black** [comment]
配置好 config.py 直接启动就可以了吗，提示 5700 端口和 go-cqhttp 冲突

**Comment by test-black** [comment]
设置了超级管理员但是提示无权限

![snipaste_20220113_202148](https://user-images.githubusercontent.com/28062894/149329441-e83b621f-3cbe-49da-8847-a84dc686aa23.png)

![image](https://user-images.githubusercontent.com/28062894/149329468-361985c3-2b99-40ee-a360-03b401290bb7.png)

**Comment by remiliacn** [comment]
> 需要用一下`！添加管理 [您的qq号]`指令 其实这个`SUPER_USER`参数是主要发日志用的

过一段时间会改进一下这里

**Comment by lilinShiro** [comment]
<img width="876" alt="微信截图_20221214112644" src="https://user-images.githubusercontent.com/105529308/207498004-26bf3992-bb1a-48a4-a8cf-02f85c0016d8.png">
大佬帮帮呜呜
