### ISSUE TITLE
请问youtube功能能否独立添加到已有的hoshinobot中？

### ISSUE THREAD

**Issue by Cathgao** [remiliacn/qqBot#14]
如YouTube开播通知、自动下源功能
hoshinobot项目地址：https://github.com/Ice-Cirno/HoshinoBot

**Comment by remiliacn** [comment]
https://github.com/remiliacn/qqBot/commit/e12e1d4bf64cfa8144c163064caec6411899d797

**Comment by remiliacn** [comment]
定时自动扒源：https://github.com/remiliacn/qqBot/blob/e12e1d4bf64cfa8144c163064caec6411899d797/awesome/plugins/get_tweet/get_tweet.py#L83-L91

定时自动提示视频更新：https://github.com/remiliacn/qqBot/blob/e12e1d4bf64cfa8144c163064caec6411899d797/awesome/plugins/get_tweet/get_tweet.py#L136-L200
