### ISSUE TITLE
冒昧的问一下，这个项目怎么跑起来啊！没学过python

### ISSUE THREAD

**Issue by LeviLuoLL** [remiliacn/qqBot#15]
是先用python.exe .\qq_bot_core.py 生成配置文件，然后也用python.exe .\qq_bot_core.py 这个把项目跑起来吗？我这边显示的是端口占用啦，cqhttp我已经跑起来了。貌似用python.exe .\qq_bot_core.py生成的配置文件的格式有点有点不对，空格多了。不知道是不是因为我pycharm的配置的原因。刚接触python，请指教，谢谢！

**Comment by remiliacn** [comment]
显示端口占用的话请更改一下配置文件PORT后面的数字。

至于空格有点多了的话可以使用SHIFT+TAB把缩进给更正一下。本项目目前还没有做直接使用的优化，所以如果直接clone项目然后直接使用的话可能会有点问题，因此不太建议刚接触Python就使用本项目的机器人。

有时间了会优化一下这方面的体验。

**Comment by remiliacn** [comment]
优化完毕，resolving。
