### ISSUE TITLE
Error:Could not find a version that satisfies the requirement kaleido

### ISSUE THREAD

**Issue by bilibilimrlei** [remiliacn/qqBot#16]
我在ARM64设备运行安装时卡在了这里，尝试手动输入以下命令安装时匜出现同样的问题`pip install kaleido`
![Screenshot_20220207-002600_UTermux](https://user-images.githubusercontent.com/56494512/152691421-39d4f658-5cc6-4827-b0d0-2351470ed052.png)
从kaleido的github的项目查看后对我来说无解，但是能看到linux_arm64的分支，现已卡在这一步无法继续，百度和谷歌都搜不到这解决方法，因此来此求问

**Comment by bilibilimrlei** [comment]
新状况，尝试使用离线安装kaleido还是失败
![Screenshot_20220207-025435_UTermux](https://user-images.githubusercontent.com/56494512/152696885-338512b8-2c12-4ea6-92e9-a143d130e254.png)

**Comment by remiliacn** [comment]
请尝试下面指令

```bash
$ python3 -m pip uninstall kaleido
$ python3 -m pip install kaleido
```

**Comment by remiliacn** [comment]
可能与以下issue有关，这边建议注释掉股票相关功能或更换服务器平台

https://github.com/plotly/Kaleido/issues/59
