### ISSUE TITLE
反向通信连接报错

### ISSUE THREAD

**Issue by shannccc** [remiliacn/qqBot#18]

**Comment by remiliacn** [comment]
可以提供报错信息么？

**Comment by shannccc** [comment]
谢谢，已经找到原因了，我没有先运行bot，所以导致连接不上






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "remiliacn/qqBot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月16日(星期六) 下午5:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [remiliacn/qqBot] 反向通信连接报错 (Issue #18)





 
可以提供报错信息么？
