### ISSUE TITLE
qq_bot_core.py运行出错

### ISSUE THREAD

**Issue by Goblinee** [remiliacn/qqBot#19]
大佬你好，我想问下这样的问题应该怎么办呢
D:\ROBOT\RB\qqBot-3.0.0>python qq_bot_core.py
Traceback (most recent call last):
  File "D:\ROBOT\RB\qqBot-3.0.0\qq_bot_core.py", line 143, in <module>
    main()
  File "D:\ROBOT\RB\qqBot-3.0.0\qq_bot_core.py", line 118, in main
    nonebot.init(config)
  File "D:\ROBOT\py\lib\site-packages\nonebot\__init__.py", line 81, in init
    _bot = NoneBot(config_object)
  File "D:\ROBOT\py\lib\site-packages\nonebot\__init__.py", line 35, in __init__
    self.asgi.debug = self.config.DEBUG
AttributeError: module 'config' has no attribute 'DEBUG'

**Comment by Goblinee** [comment]
111

**Comment by remiliacn** [comment]
请问有配置config文件么？

**Comment by Goblinee** [comment]
就配置了个超级用户和端口，请问还需要怎么配置呢，整得不是很明白🧐

**Comment by remiliacn** [comment]
参考一下这里做一下配置

https://docs.nonebot.dev/guide/basic-configuration.html

**Comment by Goblinee** [comment]
可以用了，但是为什么很多功能用不了呢

**Comment by remiliacn** [comment]
目前已知的是嘴臭和彩虹屁的接口炸了，用不了

* Pixiv需要提供账号的用户名和密码
* 模拟炒股功能需要提供Okx的密钥和api key
* 下源的话需要提供相应的下源路径

具体看一下这个sample_config.py

https://github.com/remiliacn/qqBot/blob/master/sample_config.py

**Comment by Goblinee** [comment]
每个都试了一下，好像除了闲聊类的能用，应用类或者娱乐类大部分都不能用呢，搜图，方舟10连这种都用不了捏🧐

**Comment by remiliacn** [comment]
方舟10连用不了应该是被风控了。

搜图的话要有sauce_nao的api key。
