### ISSUE TITLE
插件可以适配nonebot2.b2,吗？

### ISSUE THREAD

**Issue by krasus1995** [remiliacn/qqBot#20]

**Comment by remiliacn** [comment]
目前适配nonebot2不在开发计划中。

**Comment by remiliacn** [comment]
重开该issue，目前打算移植代码

**Comment by remiliacn** [comment]
已适配 
* https://github.com/remiliacn/qqBot/commit/5d332159aa2361e643befd6ef45065736709df08
* https://github.com/remiliacn/qqBot/commit/b46c14008cd764c5a23540dd8db302063bed31b1
