### ISSUE TITLE
使用SUPER_USER账号对bot使用指令时被回复没有权限

### ISSUE THREAD

**Issue by viomiya1** [remiliacn/qqBot#24]
qq_bot_core.py和config.py都填了超级管理员的qq，但是使用该qq私聊bot使用添加管理等指令的时候被通知没有权限，希望能解答我的问题

**Comment by viomiya1** [comment]
删去第二行 { } 之后编译成功，但是仍然没有权限

**Comment by viomiya1** [comment]
已解决

**Comment by viomiya1** [comment]
但是我三个qq只有一个能扫码成功，两个小号都没法绑定框架，不知道为什么。。。

**Comment by remiliacn** [comment]
> 但是我三个qq只有一个能扫码成功，两个小号都没法绑定框架，不知道为什么。。。

请查看[go_cqhttp](https://github.com/Mrs4s/go-cqhttp)的相关文档

**Comment by viomiya1** [comment]
sauce_nao的api key已经写了，但是使用搜图指令会回复我 “？”，然后娱乐功能也不知道怎么开启

**Comment by remiliacn** [comment]
> sauce_nao的api key已经写了，但是使用搜图指令会回复我 “？”，然后娱乐功能也不知道怎么开启

搜图时必须要在同个消息中附上图片

娱乐功能是要用这个指令：
`！设置色图禁用` 然后给`开`的参数
https://github.com/remiliacn/qqBot/blob/f9b262c9c855b3bdc3d8000ee970b0665a33cc70/awesome/plugins/setu/setu.py#L107

**Comment by viomiya1** [comment]
解决了，感谢。最后请问一下茉莉机器人的api接入之后并不能在群聊中进行设定好的互动，指令集中也没有对应指令，在plugins似乎也没有对应的功能代码，是还没有实装吗

**Comment by remiliacn** [comment]
应该是`！问题`指令调用，不过因为这个指令使用的频率实在太少，所以我有很长时间没有维护了。

https://github.com/remiliacn/qqBot/blob/06655bb9aae3e20f3129b0df503377bb532c7ffe/awesome/plugins/admin_setting/admin_setting.py#L454

**Comment by viomiya1** [comment]
修改 添加语录 后出现报错，修改回原样后依旧报错
![无标题2](https://user-images.githubusercontent.com/83017449/194734990-dc3fd5cc-1b62-4cd4-b60a-dbaa864a422c.png)

**Comment by viomiya1** [comment]
再次运行出现报错，修改过 添加语录 代码，但修改完可运行，根据网络上将match（）改为search（）等方案进行修改未见效，卸载重新部署依旧报错
![无标题3](https://user-images.githubusercontent.com/83017449/194735140-e72f9193-b40a-4333-ba90-d642ab7285bf.png)

**Comment by remiliacn** [comment]
> 再次运行出现报错，修改过 添加语录 代码，但修改完可运行，根据网络上将match（）改为search（）等方案进行修改未见效，卸载重新部署依旧报错 ![无标题3](https://user-images.githubusercontent.com/83017449/194735140-e72f9193-b40a-4333-ba90-d642ab7285bf.png)

请直接clone最新代码下来运行。这个bug应该很久前就修复好了的。

**Comment by viomiya1** [comment]
感谢大佬，已解决
这种触发词的代码储存在那个文件里呀，想扩展一下词库
以及决定怪话 指令uuid无法查询到
![无标题5](https://user-images.githubusercontent.com/83017449/194736243-ce91ee6d-0c6a-4922-b9bc-688859196471.png)
![无标题4](https://user-images.githubusercontent.com/83017449/194736256-9a1c444f-8256-4b7f-9931-bff56aefe227.png)

**Comment by remiliacn** [comment]
触发词有一些是hard coded的，那部分在natural_language组件。如果要精准回复的话，需要用！我懂了指令

然后就是uid是不需要大括号的
