### ISSUE TITLE
安装依赖的时候报错了，大佬帮帮

### ISSUE THREAD

**Issue by lilinShiro** [remiliacn/qqBot#27]
<img width="876" alt="微信截图_20221214112644" src="https://user-images.githubusercontent.com/105529308/207498441-d9ccd339-663a-4a2d-8737-48f71d913afe.png">

**Comment by remiliacn** [comment]
这是安装哪个依赖的时候出的错？

**Comment by lilinShiro** [comment]
![image](https://user-images.githubusercontent.com/105529308/207524372-7621e0ba-42c9-4a49-b9a7-bdb0251e53e0.png)
萌新不太懂，但大概是从这个位置开始的qwq

**Comment by remiliacn** [comment]
emmm没复现出来，试试upgrade PIP

**Comment by lilinShiro** [comment]
这个报错是安装了visual studio中的c++的生成器后才有的，但卸载那玩意后是这个报错，虽然已经安装过pandas但不知道为什么还是说没安装，pandas版本已经更新到1.5.2了qwq

<img width="744" alt="923c409b1079a98552c2c050cc38c02" src="https://user-images.githubusercontent.com/105529308/208216362-738db67b-4905-4d4c-928e-b28feaaadfa0.png">

**Comment by lilinShiro** [comment]
解决了，是我python版本过高的缘故，我用的3.10的版本所以会报这个错误，用3.7后依赖是可以全部跑上的

**Comment by lilinShiro** [comment]
虽然依赖跑上了但要是跑qq_bot_core.py还是会存在报错，是不是有那个库没跑上啊……这个是报的问题
PS D:\QQ1BOT\qqBot-master> python qq_bot_core.py
Traceback (most recent call last):
  File "qq_bot_core.py", line 13, in <module>
    from Services.steam_service import BuffRequester
  File "D:\QQ1BOT\qqBot-master\Services\steam_service.py", line 15, in <module>
    from config import BUFF_SESSION_ID
ImportError: cannot import name 'BUFF_SESSION_ID' from 'config' (D:\QQ1BOT\qqBot-master\config.py)

**Comment by remiliacn** [comment]
在config里加一行
`BUFF_SESSION_ID = ''` 
就可以了
