### ISSUE TITLE
想问一下大家config.py和qq_bot_core.py可以给个模板吗，不是很懂设置

### ISSUE THREAD

**Issue by namett** [remiliacn/qqBot#28]

**Comment by namett** [comment]
请问qq_bot_core.py文件不用动，设置config.py中就行了吗

**Comment by namett** [comment]
![image](https://user-images.githubusercontent.com/45278496/216535961-22951846-3503-42ae-bdaa-f24d2ba4e454.png)
在config.py中添加了一系列信息后，qq_bot_core.py没有动，任何运行报错这个

**Comment by remiliacn** [comment]
这个好像是bug，有时间修一下

**Comment by remiliacn** [comment]
可以把`steam_service.py`这个文件删掉。
