### ISSUE TITLE
佬，以下是一些功能的推荐和建议（不小心把issues放说明文档了）

### ISSUE THREAD

**Issue by baoers** [remiliacn/qqBot#31]
1、想接入gpt，用！指令触发引用gpt回复，更深入一点的话就是人物模板
（曾经用本地跑的ai模型也会带模板，但是开销太大了）
2、群语录支持关键词存储和关键词查询返图（可以用文件名命名实现？关键词后面+uuid防止重复）
3、方舟抽卡（呜）
4、色图按照热度随机返图。
已知问题：同关键词搜图重复度高。
热度（会员功能）
5、来个老婆可以捡起来搞一下，配个api，然后按照输入的关键词做图（想起来在本地也跑过novalai）
暂时这些，谢谢佬抽空帮我解决bug。
生活愉快，祝好。

**Comment by baoers** [comment]
彩虹屁的at人的指令好像有些问题

**Comment by baoers** [comment]
[stats.zip](https://github.com/user-attachments/files/16906471/stats.zip)
老大，这是一份去除了游戏送的六星、阿米娅、一星（大概）的db表，请查收！希望有帮助。

**Comment by baoers** [comment]
希望可以加上抽卡返图功能，图片可以再wiki找

**Comment by remiliacn** [comment]
1. chatgpt功能的话我自用的bot有接入，但是实现方法比较魔幻，可能得等一段时间才能生产用上
2. 这个好实现，但是原来有的语录可能要想一下怎么处理，这个我最近可以搞一下
3. 方舟抽卡有点屎山，我想以后重新写一下
4. 搜图重复度的话是因为一个关键词一页只会有30张图，如果往后找的话可能图也不会很好看，除非是那种白丝、黑丝那种很高频的关键字
5. 来个老婆那个API我有，但是那个功能和看看XP功能其实有点重复，就删掉了。

**Comment by baoers** [comment]
![image](https://github.com/user-attachments/assets/e261e6d1-a7ea-44be-a5b6-1664b08655b1)
这个好玩诶

**Comment by baoers** [comment]
关键词群语录可以使用正则包含，查出多条随机返图的逻辑

**Comment by remiliacn** [comment]
关键词语录现在是包含关系，正则的话用户门槛会稍微大一点，感觉不会是很好的用户体验

**Comment by baoers** [comment]
是逻辑可以写正则包含啦，肯定不能让用户来写呀（）

**Comment by remiliacn** [comment]
1. WIP

**Comment by remiliacn** [comment]
ChatGPT已在https://github.com/remiliacn/qqBot/commit/250a99e1ec56e38fee218be7b46cd6277a83f2db之后的commit实现

需要再config中添加新的常量`OPEN_API_KEY`

**Comment by baoers** [comment]
记得更新requirements.txt 安装openai

**Comment by remiliacn** [comment]
其它问题暂时短期内不打算解决，先close了
