### ISSUE TITLE
OneDrive相关的配置是干什么用的啊？

### ISSUE THREAD

**Issue by Thomitics** [remiliacn/qqBot#4]
OneDrive相关的配置是干什么用的啊，怎么配置？

**Comment by Thomitics** [comment]
还有那个
```python3
CANGKU_USERNAME = ''
CANGKU_PASSWORD = ''
```

**Comment by remiliacn** [comment]
OneDrive是用来自动下YouTube视频的源用的，如果不需要可以删掉。

```
CANGKU_USERNAME = ''
CANGKU_PASSWORD = ''
```

这两个是绅士仓库的登录用户名和密码，如果想要仓库搜索那个功能的话（在./awesome/plugins/setu.py里）就填上自己在绅士仓库网站的登陆用户名和密码就行了。
