### ISSUE TITLE
YouTube和Twitter相关的指令是什么

### ISSUE THREAD

**Issue by Soarniner** [remiliacn/qqBot#6]
这个Bot应该是全GitHub唯一一个能同时订阅推特和YouTube开播通知的
我朋友在看Vtuber，所以要我整一个
本人是小白，折腾了一晚上终于勉勉强强跑起来了
现在不知道订阅指令

**Comment by remiliacn** [comment]
twitter是叫跟推添加：https://github.com/remiliacn/qqBot/blob/master/awesome/plugins/get_tweet/get_tweet.py#L32
YouTube订阅的话，我刚commit上来了一个sample config，可以按自己的情况设置，然后把文件名改为`downloader.json`: https://github.com/remiliacn/qqBot/blob/master/config/downloader_sample.json
