### ISSUE TITLE
不知道为什么总是提示没有权限

### ISSUE THREAD

**Issue by Kanade1551** [remiliacn/qqBot#7]
qq_bot_core.py和config.py都填了超级管理员的qq不知道为啥还是会显示没有权限，是SUPER_USER = '******'    # 超级管理员qq号 (int)这样嘛？希望能解答下这个很低级的问题orz感谢！

**Comment by remiliacn** [comment]
使用SUPER_USER相同qq号使用`!添加管理`指令把你的那个qq号设定上管理权限就OK了。
