### ISSUE TITLE
如何关闭不需要功能

### ISSUE THREAD

**Issue by Syuvii** [remiliacn/qqBot#8]
请问大大，我不需要油管，推特，看股等的一些功能，如何去删除它们（我试着删除所有我不需要的功能，但总是出错）？同时，Services\stock.py这个文件中import Services.okex.spot_api as spot 这个导入报错

**Comment by remiliacn** [comment]
目前确实本项目缺失功能开关，这个功能其实是在之后的改进计划之中的。目前如果不需要某些功能的话建议使用IDE（如PyCharm），对功能进行一个安全删除（Safe delete）。这样可以确保所有的功能调用都能一起移除，这样应该会减少报错的可能。
